// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUJ_AgbPSUKC7l_7sZW2AGryGP_qxC-b0',
    appId: '1:221748439968:web:1f5b72316255ad567ed2c5',
    messagingSenderId: '221748439968',
    projectId: 'ramenlover0908',
    authDomain: 'ramenlover0908.firebaseapp.com',
    storageBucket: 'ramenlover0908.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDryJkiRWk1xXHOFjDy4pacD0XaO7nAY9k',
    appId: '1:221748439968:android:b148df5fea9a7cb97ed2c5',
    messagingSenderId: '221748439968',
    projectId: 'ramenlover0908',
    storageBucket: 'ramenlover0908.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8yD8UTDZCnf9_1P1joPum4KlDinNlRKA',
    appId: '1:221748439968:ios:48911ed0bd631ff57ed2c5',
    messagingSenderId: '221748439968',
    projectId: 'ramenlover0908',
    storageBucket: 'ramenlover0908.firebasestorage.app',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUJ_AgbPSUKC7l_7sZW2AGryGP_qxC-b0',
    appId: '1:221748439968:web:1f5b72316255ad567ed2c5',
    messagingSenderId: '221748439968',
    projectId: 'ramenlover0908',
    authDomain: 'ramenlover0908.firebaseapp.com',
    storageBucket: 'ramenlover0908.firebasestorage.app',
  );
}
